### ISSUE TITLE
videos of .avi format play unexpectedly fast.

### ISSUE THREAD

**Issue by hdchieh** [PaulleDemon/tkVideoPlayer#10]
I tested with master/examples/sample_player.py, and I am not sure what the problem is. Something about threads?

Python: 3.7.13
---------------------------
Package                   Version
------------------------- ---------
altgraph                  0.17.2
astroid                   2.3.3
autopep8                  1.4.4
av                        9.2.0
certifi                   2022.6.15
colorama                  0.4.1
entrypoints               0.3
flake8                    3.7.9
future                    0.18.2
imageio                   2.19.3
imageio-ffmpeg            0.4.7
importlib-metadata        4.12.0
isort                     4.3.21
lazy-object-proxy         1.4.3
mccabe                    0.6.1
numpy                     1.21.6
pandas                    1.3.5
pefile                    2022.5.30
Pillow                    9.2.0
pip                       21.2.4
pycodestyle               2.5.0
pyflakes                  2.1.1
pyinstaller               5.2
pyinstaller-hooks-contrib 2022.8
pylint                    2.4.3
python-dateutil           2.8.2
pytz                      2022.1
pywin32-ctypes            0.2.0
setuptools                61.2.0
six                       1.16.0
tkvideoplayer             2.2
typed-ast                 1.4.0
typing_extensions         4.3.0
wheel                     0.37.1
wincertstore              0.2
wrapt                     1.11.2
zipp                      3.8.0

[msvd-vid1.zip](https://github.com/PaulleDemon/tkVideoPlayer/files/9095583/msvd-vid1.zip)

**Comment by PaulleDemon** [comment]
Hi @hdchieh,  Can you provide me with more information on what error you get? copy paste the complete error traceback so I can tell you what is wrong. Thank you. (Note: if your working with python IDLE editor the editors mainloop might interfere with the programs mainloop sometimes causing errors. Its not really recommended to use the default IDLE editor, try vscode or some other)

**Comment by maru0123-2004** [comment]
In my project, it fixed with stopwatch.
Compare PyAV's Frame.time and stopwatch time.
And decide skip frame or wait or process normally.

**Comment by PaulleDemon** [comment]
@maru0123-2004 Would you mind testing the latest version from here: `pip install -i https://test.pypi.org/simple/ tkvideoplayer==2.3` . it's currently uploaded to test pypi so we can test. Can you let me know the results?

**Comment by maru0123-2004** [comment]
I test that.
I can play mp4 file.(but I think it may be fast.)

**Comment by hdchieh** [comment]
> Hi @hdchieh, Can you check this other issue out [#9 (comment)](https://github.com/PaulleDemon/tkVideoPlayer/issues/9#issuecomment-1153775858), and let me know if its the same issue. Thank you.

It's working. Thanks.
