### ISSUE TITLE
Videos at 120 FPS do not play correctly

### ISSUE THREAD

**Issue by giuseppe16180** [PaulleDemon/tkVideoPlayer#11]
First of all, thank you for your amazing work.

I have tried to use this library for playing several AVI videos. The videos in question are about 10-30 seconds long, with a resolution of 640x480 pixels at 120 FPS. Therefore, I noticed that the original videos play back slower than they should, about four times slower (I took the time with a stopwatch).

I saw that many other users experienced similar problems, so I tried the tkvideoplayer==2.3 version, but it doesn't seem to work. 

Another thing I tried was downsampling the videos to 60 and 30 FPS, and as a result the playback seems to speed up 2 and 4 times respectively.

Maybe 120 frames are too many to be processed in real time?

Any ideas? What should I do? 

Thank you.

**Comment by giuseppe16180** [comment]
I noticed that the playback also speeds up when I shrink the frame.

**Comment by PaulleDemon** [comment]
Hey thanks for creating this issue, I was working on a similar issue with respect to video playback speed. I was trying to test the new algorithm with different videos. Would you mind sharing your 120 fps video so I can look into it. Thanks.

**Comment by PaulleDemon** [comment]
@giuseppe16180 sure no problem I'll try to find some other video. Also note that resizing is done using PIL library, which might slow down things a little, may be try setting scaled option to False, in the mean time. 

Playing at 120 FPS means that we'll have to drop some frames to keep the frame rate consistent. I'll work on it and publish the changes in a few days. Thank you for ur patience.

**Comment by giuseppe16180** [comment]
I tried using the resize option to False, but the behavior does not change: when the frame is maximized the video goes slow, when I shrink the window it speeds up, the video player area also shrinks, but it crops the image (whereas before the image became smaller). It doesn't seem like a PIL problem to me, it seems due to the quality of pixels to be rendered.

Slow:

<img width="1440" alt="Schermata 2022-07-13 alle 16 34 20" src="https://user-images.githubusercontent.com/24619344/178760271-296d8911-2b36-45c8-8b9d-333a7c70e099.png">

Fast:

<img width="748" alt="Schermata 2022-07-13 alle 16 34 01" src="https://user-images.githubusercontent.com/24619344/178760250-b272dfcb-5e8e-4111-ace1-1355946223f8.png">

**Comment by PaulleDemon** [comment]
Merging this issue to #15 ,Take further discussions there.
