### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by Ora-arO** [PaulleDemon/tkVideoPlayer#21]
i'm using tkVideoPlayer to loop a video, but every time the video restart the ram usage continues to increase and reaches several gigabytes, is there any way to prevent this?

**Comment by OraSamaaa** [comment]
![image](https://user-images.githubusercontent.com/85372589/202270910-64a8cfa3-021c-4cee-b91e-f0bb7d0c18f6.png)

**Comment by PaulleDemon** [comment]
Hi @OraSamaaa,  can you let me know which version of tkvideoplayer you are using? If you are using any versions below 1.3 please update them immediately to a version greater than 1.3. Thank you.

**Comment by OraSamaaa** [comment]
2.3

**Comment by PaulleDemon** [comment]
@OraSamaaa Can you share an example code? I tried it but the memory issue doesn't seem to occur.

**Comment by PaulleDemon** [comment]
https://github.com/PaulleDemon/tkVideoPlayer/pull/33
