### ISSUE TITLE
Not able install the module 

### ISSUE THREAD

**Issue by flawless-gaming** [PaulleDemon/tkVideoPlayer#24]

**Comment by PaulleDemon** [comment]
Hello  @flawless-gaming please provide more details, such as which operating system, how you tried to install and such details. I'll close this issue for now. Please open another issue describing the above. Thank you.

**Comment by flawless-gaming** [comment]
I am using windows 7 ultimate 
I tried to install it using command ''pip install tkvideoplayer'' in cmd,
It is showing that it was unable to build a wheel for av which is required to install pyproject.toml-based project

**Comment by flawless-gaming** [comment]
> Hello  @flawless-gaming please provide more details, such as which operating system, how you tried to install and such details. I'll close this issue for now. Please open another issue describing the above. Thank you.

I am using windows 7 ultimate 
I tried to install it using command ''pip install tkvideoplayer'' in cmd,
It is showing that it was unable to build a wheel for av which is required to install pyproject.toml-based project

**Comment by PaulleDemon** [comment]
@flawless-gaming Can u check this and tell me if this helps? https://github.com/PyAV-Org/PyAV/issues/599

**Comment by flawless-gaming** [comment]
> @flawless-gaming Can u check this and tell me if this helps? https://github.com/PyAV-Org/PyAV/issues/599

Link You sent was for the cent OS 7 and
I am using windows OS 7 ultimate version

**Comment by PaulleDemon** [comment]
@flawless-gaming can you just try `pip install av` first the `pip install tkvideoplayer`, also can you tell me if you are using any virtual env?

**Comment by flawless-gaming** [comment]
> @flawless-gaming can you just try `pip install av` first the `pip install tkvideoplayer`, also can you tell me if you are using any virtual env?

I tried 'pip install av' but still it is showing the same error.
I am using Thonny as my python virtual env.

**Comment by PaulleDemon** [comment]
@flawless-gaming At this point, you need to raise that issue here: https://github.com/PyAV-Org/PyAV/issues. They can help you out better. Thank you.

**Comment by flawless-gaming** [comment]
> @flawless-gaming At this point, you need to raise that issue here: https://github.com/PyAV-Org/PyAV/issues. They can help you out better. Thank you.

Thank you for your help 
I will Raise the issue on https://github.com/PyAV-Org/PyAV/issues
