### ISSUE TITLE
Customtkinter integration?

### ISSUE THREAD

**Issue by dishb** [PaulleDemon/tkVideoPlayer#29]
Will this project ever be converted to use `customtkinter`? Or maybe somehow allow the video player to work with `ctk` apps?

**Comment by PaulleDemon** [comment]
@dishb you can easily use this with customtkinter.  Refer https://github.com/PaulleDemon/tkVideoPlayer/discussions/23#discussioncomment-4475005.

**Comment by dishb** [comment]
> @dishb you can easily use this with customtkinter. Refer [#23 (comment)](https://github.com/PaulleDemon/tkVideoPlayer/discussions/23#discussioncomment-4475005).

Did not see that for some reason 😅 Thank you!
