### ISSUE TITLE
window is not the size of the video

### ISSUE THREAD

**Issue by carlosneto726** [PaulleDemon/tkVideoPlayer#31]
The video player have fixed width = 150 and height = 100. To solve that i'd have to to manualy change the _set_frame_size() function.
![screenshot](https://github.com/PaulleDemon/tkVideoPlayer/assets/85174500/8a58073c-08f4-446a-8c56-3d10627e5d6f)

**Comment by PaulleDemon** [comment]
@carlosneto726 I am unsure what you mean by video player have fixed width and height. Could you please elaborate. You should easily be able to fill the width and height.

**Comment by carlosneto726** [comment]
let's say I want to play a video of size 1000 x 600, I call the play() function to play the video, but the video only shows in 150 X 100. Is there a way to do this? I'm sorry if I came across as ignorant or anything like that.

How it is:
![how it is](https://github.com/PaulleDemon/tkVideoPlayer/assets/85174500/5cd4c0f0-0bc8-47a8-9018-1c4a1660c4fb)

How i want:
![how i want](https://github.com/PaulleDemon/tkVideoPlayer/assets/85174500/3c06c89f-ed4e-4e32-91e1-a6daaa6f7c4e)

**Comment by Brandon4466** [comment]
I am also facing this exact same issue

**Comment by PaulleDemon** [comment]
@Brandon4466 @carlosneto726 sorry for the late reply. I am guessing you haven't resized the window. The frame resides in the window. If this is not what you meant can you create a [MRE](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by carlosneto726** [comment]
That works, thanks!
