### ISSUE TITLE
<<Loaded>> event doesnt work

### ISSUE THREAD

**Issue by reregaga** [PaulleDemon/tkVideoPlayer#5]
Thanks for creating this library, it helped me. But  when i use `<<Loaded>>` event in example below, then the metadata is not printed. But your example with loop and `<<Ended>>` event - working good. I dont know why.

```python
import tkinter as tk
from tkVideoPlayer import TkinterVideo
root = tk.Tk()
tkvideo = TkinterVideo(scaled=False, master=root)

#>>> both variants doesnt work
def showInf():
    print(tkvideo.metadata())
tkvideo.bind("<<Loaded>>", showInf) # prints the meta information
tkvideo.bind("<<Loaded>>", lambda e: print(tkvideo.video_info()), add='+') # prints duration frame rate and frame size
#<<<

tkvideo.load(r"video.mp4")
tkvideo.pack(expand=True, fill="both")
tkvideo.set_size((1200, 600)) # sets the frame size
tkvideo.play() # play the video

#>>> this variant works, when i click
def showMeta():
    print(tkvideo.metadata())
    print(tkvideo.video_info())
b = tk.Button(text="click me", command=showMeta)
b.pack()
#<<<

root.mainloop()
```
---
Libs versions:
|tkVideoPlayer|2.0.0|
|-|-|
|av | 9.2.0|
|Pillow|9.1.1|

Python 3.9.1 x64, Win10

**Comment by PaulleDemon** [comment]
Hello, @reregaga can you tell me what video file are you using? It cannot provide meta-information for some files like m4v. If you are indeed using mp4 then can you try running the file from the terminal and let me know. Thank you

**Comment by reregaga** [comment]
I add videofile and record of process, thanks for your patience!

https://user-images.githubusercontent.com/76629445/170338077-abb61659-245e-4181-9ee2-c98bc9fdf9bf.mp4


https://user-images.githubusercontent.com/76629445/170338157-dd6d90d2-70aa-4fd6-b5d2-3afb6fca8dc4.mp4

**Comment by PaulleDemon** [comment]
Hello @reregaga thanks for the video file I was able to test what you said and it indeed didn't work as expected. The solution I found was to add `tkvideo.update()` after the `tkvideo.bind("<<Loaded>>", lambda e: print(tkvideo.video_info()), add='+') ` line.
Also, note that your function `showInf` should accept an argument eg: `def showInf(event):`

Refer https://stackoverflow.com/questions/27581864/tkinters-event-generate-command-ignored for more info.

If you have any further questions or if the solution didn't work let me know. Thank you.

**Comment by reregaga** [comment]
Thanks, with `tkvideo.update()` i received output:
```python
tkvideo.bind("<<Loaded>>", lambda e: print(tkvideo.metadata()))
tkvideo.bind("<<Loaded>>", lambda e: print(tkvideo.video_info()), add='+')
tkvideo.update()

#>>> {'major_brand': 'mp42', 'minor_version': '0', 'compatible_brands': 'isomiso2avc1mp41mp42'}
#>>> {'duration': 0, 'framerate': 30, 'framesize': (0, 0)}
```
After some tests i used other events and for me final solution (get info ASAP) looks like:
```python
counter = True
def run_once(event):
    global counter
    if counter:
        print(tkvideo.video_info())
        counter = False

tkvideo.bind("<<Loaded>>", lambda e: print(tkvideo.metadata()))
tkvideo.bind("<<FrameGenerated>>", run_once, add='+')
tkvideo.update()

#>>> {'major_brand': 'mp42', 'minor_version': '0', 'compatible_brands': 'isomiso2avc1mp41mp42'}
#>>> {'duration': 23.666666666666668, 'framerate': 30, 'framesize': (640, 800)}
```
Maybe i used `<<Loaded>>` event incorrectly at first, now i found other events are intended better for special output:
| Events\Output | `major_brand` | `minor_version` | `compatible_brands` | `framerate` | `duration` | `framesize` |
|-|-|-|-|-|-|-|
|`<<Loaded>>`| ✅ | ✅ | ✅ | ✅ | | |
|`<<Duration>>` | ✅ | ✅ | ✅ | ✅ | ✅ | | 
|`<<FrameGenerated>>` | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |

**Comment by PaulleDemon** [comment]
@reregaga Thank you for posting this issue I have now updated the library to trigger the Loaded event only after reading all the information. Install `pip install tkvideoplayer==2.1` and you will only require the Loaded event to get all the information. Let me know if you have any further questions. Thank you.

**Comment by reregaga** [comment]
I installed version 2.1 and now it works:
```python
tkvideo.bind("<<Loaded>>", lambda e: print(tkvideo.metadata()), add='+')
tkvideo.bind("<<Loaded>>", lambda e: print(tkvideo.video_info()), add='+')
#>>> {'major_brand': 'mp42', 'minor_version': '0', 'compatible_brands': 'isomiso2avc1mp41mp42'}
#>>> {'duration': 23.666666666666668, 'framerate': 30, 'framesize': (640, 800)}
```
Thanks a lot for the quick fix!
