### ISSUE TITLE
error when install tkvideoplayer

### ISSUE THREAD

**Issue by Numbbbbbbbb** [PaulleDemon/tkVideoPlayer#52]
I try to install tkvideoplayer but it keep having error.
This is my error message below

pip install tkvideoplayer
Collecting tkvideoplayer
  Using cached tkvideoplayer-2.8-py3-none-any.whl.metadata (3.2 kB)
Collecting av==9.2.0 (from tkvideoplayer)
  Using cached av-9.2.0.tar.gz (2.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

**Comment by PaulleDemon** [comment]
Which version of python are you using? If you are using python 3.11 or above, you will encounter this error because pyav 9.2 doesn't support python 3.11 see #47

**Comment by Numbbbbbbbb** [comment]
I'm using python 3.11 now

**Comment by PaulleDemon** [comment]
@Numbbbbbbbb so please go with 3.10, its currently being used by most of the industry.
