### ISSUE TITLE
AI agent trained on Repo Code + Issues

### ISSUE THREAD

**Issue by samyakkkk** [PaulleDemon/tkVideoPlayer#55]
Hi @PaulleDemon!

We are a marketplace of AI agents trained on Github Repos + Issues of popular OSS projects to help devs:

1. Ask specific + general questions on it's codebase. 
2. Look for specific issues related to their problem.
3. Understand it better to make contributions.
4. Get help building with your project.

We recently enabled the [agent](https://app.commanddash.io/agent?github=https://github.com/PaulleDemon/tkVideoPlayer) for your repo 🙌🏼 If it could be helpful to others, you can mention this in your readme as a badge:

<a href="https://app.commanddash.io/agent?github=https://app.commanddash.io/agent?github=https://github.com/PaulleDemon/tkVideoPlayer"><img src="https://img.shields.io/badge/AI-Code%20Assist-EB9FDA"></a>

```md
<a href="https://app.commanddash.io/agent?github=https://app.commanddash.io/agent?github=https://github.com/PaulleDemon/tkVideoPlayer"><img src="https://img.shields.io/badge/AI-Code%20Assist-EB9FDA"></a>
```

If not, please mark the issue as closed. Best Regards.

**Comment by PaulleDemon** [comment]
Hi, 
Thanks,  unfortunately, I don't understand the difference of not having it for this repo.

Going forward, You should put a demo video along, if you really want people to understand the USP of your project.

Best
