### ISSUE TITLE
Scale problem

### ISSUE THREAD

**Issue by Akascape** [PaulleDemon/tkVideoPlayer#7]
I got another error in tkVideoPlayer's scaled parameter, when we set scaled to True it works and the video fits with the label size, but I don't want stretching in videos so I set scaled to False but it is giving lots of errors. 
Can we fit the video on the label with original ratio but with other remaining portions as black/label color?
And the set_scaled parameter is also not working.

**Comment by PaulleDemon** [comment]
@Akascape I have updated the library. Try tkvideoplayer 2.2: https://pypi.org/project/tkvideoplayer/2.2/ .Let me know if you find any issues, Now I have added the ability to keep the aspect ratio, refer docs [here](https://github.com/PaulleDemon/tkVideoPlayer/blob/master/Documentation.md), you can then use `tkvideo.config(bg="black")` to get a black background.

**Comment by Akascape** [comment]
Thanks, its now working properly :)
