### ISSUE TITLE
How to pause and seek at a moment?

### ISSUE THREAD

**Issue by Akascape** [PaulleDemon/tkVideoPlayer#8]
I am a little bit confused on the seek method, when I seek to a part while the video is paused then it doesn't display the frame, means it only displays the seeked part when it is played.
I tried this method after seek while pausing the video and it worked but we have to use the time module and I think its not accurate;
``` python
vid_player.seek(int(5)) 
vid_player.play()
time.sleep(0.1)
vid_player.pause()
 ```
Any fix for this? I just want to display the video frame when seeked without playing it.

**Comment by Akascape** [comment]
@PaulleDemon I tried this method but it was not working. Thats why I used the time method. Please let me know if this is happening in your system also. 
The pause method just pauses the video while playing but don't seek to the frame.

**Comment by PaulleDemon** [comment]
@Akascape Hmm sorry I hadn't tested that, my laptop is given for repair. I am using my phone so you can probably give this code a shot.

```py
def seek(sec):
    vid_player.seek(sec)
    vid_player.after(5, vid_player.pause) # test this, the first parameter is time in milliseconds, u can change this according to ur need.

seek(20)    
```

**Comment by Akascape** [comment]
@PaulleDemon It worked but we have to add another line:
```python
def seek(sec):
    vid_player.seek(sec)
    vid_player.play() #have to play it so that it display the seeked frame
    vid_player.after(50, vid_player.pause)
seek(20)  ```
